version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres_teste
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "54320:5432" # Porta mapeada para o host
    volumes:
      - db_data:/var/lib/postgresql/data # Persistência de dados
      - ./scripts:/docker-entrypoint-initdb.d/ # Scripts SQL automáticos

volumes:
  db_data:
    driver: local
